namespace Common.Requests;

public record CreateAtendimentoPlantao(
    int Atd_usu_identi,
    int Atd_ptd_identi,
    int Atd_cli_identi,
    String Atd_tipatd,
    int Atd_cat_identi,
    String Atd_resumo,
    String Atd_respn2,
    String Atd_crijir,
    String Atd_issue,
    String Atd_critic,
    String Atd_resplt,
    String Atd_ren1hm,
    String Atd_resn1,
    String Atd_evoln1,
    String Atd_observ,
    String Atd_usubdd,
    DateTime Atd_datatd,
    String Atd_nomal2,
    String Atd_status,
    int Atd_usucri,
    int Atd_usualt,
    DateTime Atd_datcri,
    DateTime Atd_datalt
);

public record UpdateAtendimentoPlantao(
    int Id,
    int Atd_usu_identi,        
    int Atd_cli_identi,
    String Atd_tipatd,
    int Atd_cat_identi,
    String Atd_resumo,
    String Atd_respn2,
    String Atd_crijir,
    String Atd_issue,
    String Atd_critic,
    String Atd_resplt,
    String Atd_ren1hm,
    String Atd_resn1,
    String Atd_evoln1,
    String Atd_observ,
    String Atd_usubdd,
    DateTime Atd_datatd,
    String Atd_nomal2,
    String Atd_status,
    int Atd_usucri,
    int Atd_usualt,
    DateTime Atd_datcri,
    DateTime Atd_datalt
);